//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34209
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Brainary.Commons {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Brainary.Commons.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Locator is already initialized.
        /// </summary>
        public static string AlreadyInitializedLocator {
            get {
                return ResourceManager.GetString("AlreadyInitializedLocator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ambiguous invocation of &apos;{0}&apos; constructor.
        /// </summary>
        public static string AmbiguousConstructorInvocation {
            get {
                return ResourceManager.GetString("AmbiguousConstructorInvocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ambiguous invocation of indexer in type &apos;{0}&apos;.
        /// </summary>
        public static string AmbiguousIndexerInvocation {
            get {
                return ResourceManager.GetString("AmbiguousIndexerInvocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ambiguous invocation of method &apos;{0}&apos; in type &apos;{1}&apos;.
        /// </summary>
        public static string AmbiguousMethodInvocation {
            get {
                return ResourceManager.GetString("AmbiguousMethodInvocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &apos;{0}&apos; Key was not found in appSettings section.
        /// </summary>
        public static string AppSettingNotFound {
            get {
                return ResourceManager.GetString("AppSettingNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Argument list incompatible with lambda expression.
        /// </summary>
        public static string ArgsIncompatibleWithLambda {
            get {
                return ResourceManager.GetString("ArgsIncompatibleWithLambda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a At least one value is required in &apos;{0}&apos; group.
        /// </summary>
        public static string AtLeastOneRequired {
            get {
                return ResourceManager.GetString("AtLeastOneRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Both of the types &apos;{0}&apos; and &apos;{1}&apos; convert to the other.
        /// </summary>
        public static string BothTypesConvertToOther {
            get {
                return ResourceManager.GetString("BothTypesConvertToOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Call to {0}.{1}.
        /// </summary>
        public static string CallTo {
            get {
                return ResourceManager.GetString("CallTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A value of type &apos;{0}&apos; cannot be converted to type &apos;{1}&apos;.
        /// </summary>
        public static string CannotConvertValue {
            get {
                return ResourceManager.GetString("CannotConvertValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Indexing of multi-dimensional arrays is not supported.
        /// </summary>
        public static string CannotIndexMultiDimArray {
            get {
                return ResourceManager.GetString("CannotIndexMultiDimArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &apos;]&apos; or &apos;,&apos; expected.
        /// </summary>
        public static string CloseBracketOrCommaExpected {
            get {
                return ResourceManager.GetString("CloseBracketOrCommaExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &apos;)&apos; or &apos;,&apos; expected.
        /// </summary>
        public static string CloseParenOrCommaExpected {
            get {
                return ResourceManager.GetString("CloseParenOrCommaExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &apos;)&apos; or operator expected.
        /// </summary>
        public static string CloseParenOrOperatorExpected {
            get {
                return ResourceManager.GetString("CloseParenOrOperatorExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &apos;:&apos; expected.
        /// </summary>
        public static string ColonExpected {
            get {
                return ResourceManager.GetString("ColonExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ConnectionString &apos;{0}&apos; was not found.
        /// </summary>
        public static string ConnectionStringNotFound {
            get {
                return ResourceManager.GetString("ConnectionStringNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Property DescriptionsCommand is not set.
        /// </summary>
        public static string DescriptionsCommandNotSet {
            get {
                return ResourceManager.GetString("DescriptionsCommandNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Digit expected.
        /// </summary>
        public static string DigitExpected {
            get {
                return ResourceManager.GetString("DigitExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &apos;.&apos; or &apos;(&apos; expected.
        /// </summary>
        public static string DotOrOpenParenExpected {
            get {
                return ResourceManager.GetString("DotOrOpenParenExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The identifier &apos;{0}&apos; was defined more than once.
        /// </summary>
        public static string DuplicateIdentifier {
            get {
                return ResourceManager.GetString("DuplicateIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Elapsed: {0}.
        /// </summary>
        public static string Elapsed {
            get {
                return ResourceManager.GetString("Elapsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exception at {0}.{1}.
        /// </summary>
        public static string ExceptionAt {
            get {
                return ResourceManager.GetString("ExceptionAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Expression expected.
        /// </summary>
        public static string ExpressionExpected {
            get {
                return ResourceManager.GetString("ExpressionExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Expression of type &apos;{0}&apos; expected.
        /// </summary>
        public static string ExpressionTypeMismatch {
            get {
                return ResourceManager.GetString("ExpressionTypeMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The first expression must be of type &apos;Boolean&apos;.
        /// </summary>
        public static string FirstExprMustBeBool {
            get {
                return ResourceManager.GetString("FirstExprMustBeBool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Identifier expected.
        /// </summary>
        public static string IdentifierExpected {
            get {
                return ResourceManager.GetString("IdentifierExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The &apos;iif&apos; function requires three arguments.
        /// </summary>
        public static string IifRequiresThreeArgs {
            get {
                return ResourceManager.GetString("IifRequiresThreeArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Operator &apos;{0}&apos; incompatible with operand type &apos;{1}&apos;.
        /// </summary>
        public static string IncompatibleOperand {
            get {
                return ResourceManager.GetString("IncompatibleOperand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Operator &apos;{0}&apos; incompatible with operand types &apos;{1}&apos; and &apos;{2}&apos;.
        /// </summary>
        public static string IncompatibleOperands {
            get {
                return ResourceManager.GetString("IncompatibleOperands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Locator has not been initialized, you must call Initialize method first.
        /// </summary>
        public static string InitializeLocatorFirst {
            get {
                return ResourceManager.GetString("InitializeLocatorFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Syntax error &apos;{0}&apos;.
        /// </summary>
        public static string InvalidCharacter {
            get {
                return ResourceManager.GetString("InvalidCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Character literal must contain exactly one character.
        /// </summary>
        public static string InvalidCharacterLiteral {
            get {
                return ResourceManager.GetString("InvalidCharacterLiteral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Field &apos;{0}&apos; is invalid.
        /// </summary>
        public static string InvalidField {
            get {
                return ResourceManager.GetString("InvalidField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Array index must be an integer expression.
        /// </summary>
        public static string InvalidIndex {
            get {
                return ResourceManager.GetString("InvalidIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid integer literal &apos;{0}&apos;.
        /// </summary>
        public static string InvalidIntegerLiteral {
            get {
                return ResourceManager.GetString("InvalidIntegerLiteral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid real literal &apos;{0}&apos;.
        /// </summary>
        public static string InvalidRealLiteral {
            get {
                return ResourceManager.GetString("InvalidRealLiteral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Method &apos;{0}&apos; in type &apos;{1}&apos; does not return a value.
        /// </summary>
        public static string MethodIsVoid {
            get {
                return ResourceManager.GetString("MethodIsVoid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Methods on type &apos;{0}&apos; are not accessible.
        /// </summary>
        public static string MethodsAreInaccessible {
            get {
                return ResourceManager.GetString("MethodsAreInaccessible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Expression is missing an &apos;as&apos; clause.
        /// </summary>
        public static string MissingAsClause {
            get {
                return ResourceManager.GetString("MissingAsClause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Object reference not set to an instance of an object.
        /// </summary>
        public static string MissingObjectInstance {
            get {
                return ResourceManager.GetString("MissingObjectInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} must be greater or equal {1}.
        /// </summary>
        public static string MustBeGreaterOrEqual {
            get {
                return ResourceManager.GetString("MustBeGreaterOrEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} must be greater than {1}.
        /// </summary>
        public static string MustBeGreaterThan {
            get {
                return ResourceManager.GetString("MustBeGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} must be less or equal {1}.
        /// </summary>
        public static string MustBeLessOrEqual {
            get {
                return ResourceManager.GetString("MustBeLessOrEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} must be less than {1}.
        /// </summary>
        public static string MustBeLessThan {
            get {
                return ResourceManager.GetString("MustBeLessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The field {0} must contain only digits.
        /// </summary>
        public static string MustContainOnlyDigits {
            get {
                return ResourceManager.GetString("MustContainOnlyDigits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Neither of the types &apos;{0}&apos; and &apos;{1}&apos; converts to the other.
        /// </summary>
        public static string NeitherTypeConvertsToOther {
            get {
                return ResourceManager.GetString("NeitherTypeConvertsToOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No applicable aggregate method &apos;{0}&apos; exists.
        /// </summary>
        public static string NoApplicableAggregate {
            get {
                return ResourceManager.GetString("NoApplicableAggregate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No applicable indexer exists in type &apos;{0}&apos;.
        /// </summary>
        public static string NoApplicableIndexer {
            get {
                return ResourceManager.GetString("NoApplicableIndexer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No applicable method &apos;{0}&apos; exists in type &apos;{1}&apos;.
        /// </summary>
        public static string NoApplicableMethod {
            get {
                return ResourceManager.GetString("NoApplicableMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No &apos;it&apos; is in scope.
        /// </summary>
        public static string NoItInScope {
            get {
                return ResourceManager.GetString("NoItInScope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No matching constructor in type &apos;{0}&apos;.
        /// </summary>
        public static string NoMatchingConstructor {
            get {
                return ResourceManager.GetString("NoMatchingConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &apos;[&apos; expected.
        /// </summary>
        public static string OpenBracketExpected {
            get {
                return ResourceManager.GetString("OpenBracketExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &apos;(&apos; expected.
        /// </summary>
        public static string OpenParenExpected {
            get {
                return ResourceManager.GetString("OpenParenExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The field {0} must be between {1} and {2}.
        /// </summary>
        public static string OutOfRange {
            get {
                return ResourceManager.GetString("OutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} (at index {1}).
        /// </summary>
        public static string ParseExceptionFormat {
            get {
                return ResourceManager.GetString("ParseExceptionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The {0} field is required.
        /// </summary>
        public static string RequiredField {
            get {
                return ResourceManager.GetString("RequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error serializing arguments.
        /// </summary>
        public static string SerializeArgumentsError {
            get {
                return ResourceManager.GetString("SerializeArgumentsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Syntax error.
        /// </summary>
        public static string SyntaxError {
            get {
                return ResourceManager.GetString("SyntaxError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a the actual date.
        /// </summary>
        public static string TheActualDate {
            get {
                return ResourceManager.GetString("TheActualDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} expected.
        /// </summary>
        public static string TokenExpected {
            get {
                return ResourceManager.GetString("TokenExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Type &apos;{0}&apos; has no nullable form.
        /// </summary>
        public static string TypeHasNoNullableForm {
            get {
                return ResourceManager.GetString("TypeHasNoNullableForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unknown identifier &apos;{0}&apos;.
        /// </summary>
        public static string UnknownIdentifier {
            get {
                return ResourceManager.GetString("UnknownIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No property or field &apos;{0}&apos; exists in type &apos;{1}&apos;.
        /// </summary>
        public static string UnknownPropertyOrField {
            get {
                return ResourceManager.GetString("UnknownPropertyOrField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unterminated string literal.
        /// </summary>
        public static string UnterminatedStringLiteral {
            get {
                return ResourceManager.GetString("UnterminatedStringLiteral", resourceCulture);
            }
        }
    }
}
